# Generated by Django 4.2.10 on 2024-03-02 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0415_alter_medibasemedicine_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medibasemedicine",
            name="external_id",
        ),
    ]
