# Generated by Django 4.2.10 on 2024-03-02 14:56
from django.core.management import call_command
from django.db import migrations


def update_ids(apps, schema_editor):
    MedibaseMedicine = apps.get_model("facility", "MedibaseMedicine")
    offset = 90000

    for medicine in MedibaseMedicine.objects.all():
        new_id = medicine.id + offset

        # Create a new instance with updated ID using update_or_create
        MedibaseMedicine.objects.update_or_create(
            id=new_id,
            defaults={
                "created_date": medicine.created_date,
                "modified_date": medicine.modified_date,
                "deleted": medicine.deleted,
                "name": medicine.name + "_",
                "type": medicine.type,
                "generic": medicine.generic,
                "company": medicine.company,
                "contents": medicine.contents,
                "cims_class": medicine.cims_class,
                "atc_classification": medicine.atc_classification,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0416_remove_medibasemedicine_external_id"),
    ]

    operations = [
        migrations.RunPython(update_ids),
        migrations.RunPython(
            lambda apps, schema_editor: call_command("load_medicines_data"),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
