# Generated by Django 4.2.10 on 2024-03-09 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0416_patientconsultation_unique_patient_no_within_facility"),
        ("facility", "0416_update_facility_types"),
    ]

    operations = []
