# Generated by Django 5.1.1 on 2024-11-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0467_alter_hospitaldoctors_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_class',
            field=models.CharField(blank=True, choices=[('HL7MONITOR', 'hl7monitor'), ('VENTILATOR', 'ventilator')], default=None, max_length=20, null=True),
        ),
    ]
