# Generated by Django 5.1.1 on 2024-11-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0468_alter_asset_asset_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CameraPreset',
        ),
    ]
