# Generated by Django 5.1.3 on 2024-12-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0469_alter_asset_asset_class_alter_asset_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbed',
            name='is_privacy_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
